apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product
  replicas: 3
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-server
        image: product_server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "256m"
          limits:
            memory: "128Mi"
            cpu: "512m"